services:
  livekit-server:
    image: livekit/livekit-server:latest
    restart: always
    ports:
      - "7880:7880"   # HTTP API e WebSocket (wss)
    environment:
      - LIVEKIT_CONFIG_FILE=/etc/livekit.yaml
      - "LIVEKIT_KEYS=APIgNxWzk3h8fpH: eTMC1y4k94cOyo1Y1zj5i0eVO6eGoe75CIjebOg4j6bB"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    depends_on:
      - redis
    labels:
      - "caddy=livekit.doctorkit.satmed.net"
      - "caddy.reverse_proxy={{upstreams 7880}}"
      - "caddy.tls=internal"
      - "caddy.encode=gzip"
    networks:
      - livekit

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - livekit

networks:
  livekit:
    driver: bridge
