# Coolify-optimized LiveKit Server Setup
# This version removes the Caddy L4 proxy and lets Coolify handle TLS termination
services:
  livekit-server:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    restart: unless-stopped
    expose:
      - "7880"   # HTTP/WebSocket API (internal)
      - "7881"   # TCP for WebRTC media (internal)
    ports:
      - "10000-10100:10000-10100/udp" # UDP media (needs host ports for WebRTC)
    environment:
      - LIVEKIT_CONFIG_FILE=/config/livekit.yaml
      - "LIVEKIT_KEYS=APIgNxWzk3h8fpH: eTMC1y4k94cOyo1Y1zj5i0eVO6eGoe75CIjebOg4j6bB"
    volumes:
      - ./livekit.yaml:/config/livekit.yaml
    depends_on:
      - redis
    networks:
      - livekit-net
    labels:
      # Coolify labels for HTTP API
      - "coolify.managed=true"
      - "coolify.name=livekit-api"
      - "coolify.http.main.loadbalancer.server.port=7880"
      - "coolify.type=service"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - livekit-net
    labels:
      - "coolify.managed=true"

networks:
  livekit-net:
    driver: bridge
